{{- if and .Values.backend.enabled .Values.backend.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "feastfrenzy.backend.serviceAccountName" . }}
  labels:
    {{- include "feastfrenzy.backend.labels" . | nindent 4 }}
  {{- with .Values.backend.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}

{{- if and .Values.frontend.enabled .Values.frontend.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "feastfrenzy.frontend.serviceAccountName" . }}
  labels:
    {{- include "feastfrenzy.frontend.labels" . | nindent 4 }}
  {{- with .Values.frontend.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
